jeu/urls.py
# coding=utf-8
from django.urls import path
from .views import searchgame, GameListView, GameDetailView, GameDeleteView, GameUpdateView, GameCreateView

app_name = 'jeu'
urlpatterns = [
    path(r'addnew', searchgame, name="addnew"),
    path(r'search', GameListView.as_view(), name="search"),
    path(r'addnew/<slug:dbsearch>/<slug:db_id>', GameCreateView.as_view(), name="create"),
    path(r'<int:game_id>', GameDetailView.as_view(), name="detail"),
    path(r'update/<int:game_id>', GameUpdateView.as_view(), name="update"),
    path(r'delete/<int:game_id>', GameDeleteView.as_view(), name="delete"),
]

ludogo/urls.py
# coding=utf-8
"""ludogo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path(r'', HomeView.as_view(), name="home"),
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'movie/', include('film.urls', namespace="film")),
    path(r'game/', include('jeu.urls', namespace="jeu")),
]

jeu/models.py
from django.db import models
from common.models import Genre, Person, Localisation

# Create your models here.


class Game(models.Model):
    title = models.CharField(max_length=300, help_text='Nom du jeu', unique=True)
    description = models.TextField(help_text='description du jeu')
    genres = models.ManyToManyField(Genre, help_text='genres du jeu')
    date = models.DateTimeField()
    creators = models.ManyToManyField(Person, help_text='createurs du jeu', related_name='creators')
    tarif = models.FloatField(null=True)
    localisation = models.ForeignKey(Localisation, help_text="lieu où est le film", on_delete=models.DO_NOTHING)
    playersmin = models.IntegerField(help_text='Nombre de joueurs minimum')
    playersmax = models.IntegerField(help_text='Nombre de joueurs maximum')
    timemin = models.IntegerField(null=True, help_text='temps de jeu minimum')
    timemax = models.IntegerField(null=True, help_text='temps de jeu maximum')
    agemin = models.IntegerField(null=True, help_text='age minimum')
    extension = models.BooleanField(default=False, help_text="Est ce que ce jeu est une extension d'un autre?")


    def __str__(self):
        return self.title

jeu/forms.py
from django.forms.models import ModelForm
from django import forms
from .models import Game
from common.models import Genre, Person


class GameForm(ModelForm):

    date = forms.DateField(
        widget=forms.DateInput(format='%Y', attrs={'class': 'datepicker'}),
        input_formats=('%Y',)
    )

    def __init__(self, *args, **kwargs):
        super(GameForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.label in ['Extension']:
                visible.field.widget.attrs['class'] = ''
            else:
                visible.field.widget.attrs['class'] = 'form-control'
            if visible.field.label in ['Title', 'Genres', 'Localisation', 'Playersmin', 'Playersmax', 'Creators',
                                       'Date']:
                visible.field.required = True
            else:
                visible.field.required = False
            if visible.field.label in ['Creators','Genres']:
                visible.field.widget.attrs['size'] = 10
        self.fields['genres'].queryset = Genre.objects.filter(type=Genre.TYPE_GAME)
        self.fields['creators'].queryset = Person.objects.all().order_by('firstname')

    class Meta:
        model = Game
        fields = ('title', 'description', 'genres', 'date', 'creators', 'tarif', 'localisation', 'playersmin',
                  'playersmax', 'timemin', 'timemax', 'agemin', 'extension')
        widgets = {
            'creators': forms.SelectMultiple,
        }


class GameListForm(ModelForm):
    search_field = forms.CharField(max_length=250)

jeu/views.py
# coding=utf-8
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Q, Sum
from .models import Game
from .forms import GameForm, GameListForm
from common.models import Person
from django.urls import reverse_lazy
from bs4 import BeautifulSoup
import requests
import datetime

URL_REQUEST_TTF = 'https://www.tabletopfinder.eu/fr/boardgame/search'
URL_HTML_TTF = 'https://www.tabletopfinder.eu/fr/boardgame/{}/'

URL_REQUEST_TRICTRAC = 'https://www.trictrac.net/recherche'
URL_HTML_TRICTRAC = 'https://www.trictrac.net/jeu-de-societe/{}'
# Create your views here.


class GameDetailView(generic.DetailView):
    model = Game
    pk_url_kwarg = 'game_id'


class GameUpdateView(generic.UpdateView):
    model = Game
    form_class = GameForm
    pk_url_kwarg = 'game_id'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy("jeu:detail")

    def get_success_url(self):
        return reverse_lazy('jeu:detail', kwargs=self.kwargs)

def getfromttf(dbid):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
    url = URL_HTML_TTF.format(dbid)
    htmlresult = requests.get(url, headers=headers)
    soupresult = BeautifulSoup(htmlresult.text)
    header = soupresult.find('div', attrs={'id': 'product-header'})
    details = soupresult.find('div', attrs={'id': 'product-properties'})
    tarifs = soupresult.find('div', attrs={'id': 'product-prices'})
    title = header.find_next('h1')
    if title:
        title = title.text
    descriptions = header.find_all('p')
    description = []
    for desc in descriptions:
        description.append(desc.text)
    description = "'\n".join(description)

    tarif = None
    agemin = None
    date = None
    listcreat = []
    players = header.find_next('div', attrs={'title': 'joueurs', 'class': 'tag'})
    playersmin = players.text.split('-')[0].strip()
    if len(players.text.split('-')) > 1:
        playersmax = players.text.split('-')[1].strip()
    else:
        playersmax = playersmin
    times = header.find_next('div', attrs={'title': 'temps', 'class': 'tag'})
    timemax = times.text.split('-')[1].strip()
    if len(times.text.split('-')) > 1:
        timemin = times.text.split('-')[0].strip()
    else:
        timemin = timemax
    tables = details.findAll('tr')
    for tr in tables:
        if tr.find_next('th').text == "Publié:":
            try:
                date = int(tr.find_next('td').text)
            except ValueError:
                date = int(tr.find_next('td').text.split()[1])
        if tr.find_next('th').text == "Concepteurs:":
            liconcepteurs = tr.findAll('li')
            if liconcepteurs:
                for concepteur in liconcepteurs:
                    name = concepteur.find('a').text.strip('\n').strip().split(' ')
                    creat = Person.objects.get_or_create(firstname=' '.join(name[0:-1]), lastname=name[-1])
                    listcreat.append(creat[0].id)
            else:
                name = tr.find('a').text.strip('\n').strip().split(' ')
                if name:
                    creat = Person.objects.get_or_create(firstname=' '.join(name[0:-1]), lastname=name[-1])
                    listcreat.append(creat[0].id)
    prix = tarifs.findAll('tr')
    for tr in prix:
        tds = tr.findAll('td')
        if len(tds) >= 3:
            if tds[2].text.strip():
                pricetd = tds[2]
                if pricetd.find('small'):
                    pricetd.find('small').decompose()
                if pricetd.text.strip():
                    tarif = pricetd.text.strip().split(u'\xa0')[1].strip()
        if tarif:
            break

    urls = [url, "{}?query={}".format(URL_REQUEST_TTF, title.replace(' ', '+').lower())]
    newgame = {'title': title, 'description': description, 'date': datetime.datetime(date, 1, 1),
               'creators': listcreat, 'agemin': agemin, 'playersmin': playersmin, 'playersmax': playersmax,
               'timemin': timemin, 'timemax': timemax, 'tarif': tarif}
    return newgame, urls

def getfromtrictrac(dbid):
    url = URL_HTML_TRICTRAC.format(dbid)
    htmlresult = requests.get(url)
    soupresult = BeautifulSoup(htmlresult.text)
    agemin = None
    playersmin = None
    playersmax = None
    timemin = None
    timemax = None
    tarif = None
    date = None
    listcreat = []
    title = soupresult.find('h1', attrs={"itemprop":"name", "class": "game-title"})
    if title:
        title = title.find_next('a').text.strip()
    divdescript =  soupresult.find('div', attrs={'itemprop': 'description'})
    description = divdescript.find_next('p').text.replace('<br>','\n')
    casting = soupresult.find('div', attrs={'class': 'casting'})
    details = soupresult.findAll('div', attrs={'class': 'part'})
    shop = soupresult.find('div', attrs={'class': 'shops'})
    aref = casting.find_all('a')
    par = 0
    for a in aref:
        if 'Par' in a.previous:
            par = 1
            name = a.text.strip().split()
            creat = Person.objects.get_or_create(firstname=' '.join(name[0:-1]), lastname=name[-1])
            listcreat.append(creat[0].id)
        if ',' in a.previous and par:
            name = a.text.strip().split()
            creat = Person.objects.get_or_create(firstname=' '.join(name[0:-1]), lastname=name[-1])
            listcreat.append(creat[0].id)
        if 'et' in a.previous and par:
            name = a.text.strip().split()
            creat = Person.objects.get_or_create(firstname=' '.join(name[0:-1]), lastname=name[-1])
            listcreat.append(creat[0].id)
            break
    for detail in details:
        hdetail = detail.find_next('h4')
        if hdetail.text == "Détails":
            divdetail = hdetail.find_next("div")
            date = int(divdetail.text.split(u'\xa0')[-1].strip())

    gameplay = soupresult.find('div', attrs={'class':'gameplay'})
    if gameplay:
        gameplay = gameplay.find_all('div', attrs={"class": "stat mini"})
        for play in gameplay:
            if play.find_next("div", attrs={"class": "sub"}).text == "Joueurs":
                players = play
                players.find_next('span').decompose()
                players.find_next('div', attrs={'class': 'sub'}).decompose()
                if players.text:
                   players = players.text.split('à')
                   playersmin = players[0].strip()
                   playersmax = players[1].strip()
                continue
            if play.find_next("div", attrs={"class": "sub"}).text == "Âge":
                agemintemp = play
                agemintemp.find_next('div', attrs={'class': 'sub'}).decompose()
                if agemintemp.text:
                    agemintemp = agemintemp.text
                    if "ans et +" in agemintemp:
                        agemin = agemintemp.strip('ans et +').strip()
                    elif " à " in agemintemp:
                        agemin = agemintemp.split('à')[0].strip()
                continue
            if play.find_next("div", attrs={"class": "sub"}).text == "Temps de partie":
                timemintemp = play
                timemintemp.find_next('span').decompose()
                timemintemp.find_next('div', attrs={'class': 'sub'}).decompose()
                if timemintemp.text:
                     timemin = timemintemp.text.strip()
                     timemax = timemin
                continue
    if shop:
        tarif = shop.find_next('div', attrs={'class': 'stat small'})
        if tarif:
            tarif.find_next('span').decompose()
            tarif = tarif.text.strip().split(u'\xa0')[0].replace(',','.')
    urls = [url, "{}?query={}&limit=20".format(URL_REQUEST_TRICTRAC, dbid)]
    newgame = {'title': title, 'description': description, 'date': date,
               'creators': listcreat, 'agemin': agemin, 'playersmin': playersmin, 'playersmax': playersmax,
               'timemin': timemin, 'timemax': timemax, 'tarif': tarif}
    return newgame, urls


class GameCreateView(generic.CreateView):
    model = Game
    form_class = GameForm
    template_name_suffix = '_update_form'

    def get_initial(self):
        #TODO: delete old messages
        #storage = messages.get_messages(self.request)
        #storage.used = True
        #if len(storage._loaded_messages) == 3: 
        #    del storage._loaded_messages[0]
        #    del storage._loaded_messages[1]
        #    del storage._loaded_messages[2]
        if self.kwargs['db_id'] != 'empty':
            if self.kwargs['dbsearch'] == 'ttf':
                newgame, urls = getfromttf(self.kwargs['db_id'])
                messages.add_message(self.request, messages.INFO, '{}'.format(urls[0]))
                messages.add_message(self.request, messages.INFO, '{}'.format(urls[1]))
            elif self.kwargs['dbsearch'] == 'trictrac':
                newgame, urls = getfromtrictrac(self.kwargs['db_id'])
                messages.add_message(self.request, messages.INFO, '{}'.format(urls[0]))
                messages.add_message(self.request, messages.INFO, '{}'.format(urls[1]))
            else:
                newgame = {}

        else:
            newgame = {}
        return newgame

    def get_success_url(self):
        return reverse_lazy('jeu:detail', kwargs={'game_id':self.object.pk})

def ttfsearch(query):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
    payload = {'query': query.replace(' ', '+').lower(), 'page': 1}
    result = requests.get(URL_REQUEST_TTF, params=payload, headers=headers)
    #result = result.json()
    soupresult = BeautifulSoup(result.text)
    results = soupresult.find('div', class_="results")
    items = results.find_all('a', href=True)
    #payload = {'query': query.replace(' ', '+').lower(), 'page': 2}

jeu/templates/jeu/addnew_game.html
{% extends "common/base.html" %}

{% block content %}
<form method="get" action="{% url 'jeu:addnew' %}">
    <div class="container">
    <div class="card border-success">
        <div class="card-header text-center text-white bg-success"><h3>Nom du jeu à ajouter</h3></div>
        <div class="card-body">
          <input class="form-control" id="id_newgame"
                 placeholder="Entrez un titre" type="text" name="newgame"
                 value="{{ newgametitle }}"
                 aria-describedby="newgameHelp"/>
          <small id="newgameHelp" class="form-text text-muted">un titre complet ou juste un morceau du titre est suffisant
          </small>
            <!-- Material inline 1 -->
          <div class="form-check form-check-inline">
              <input type="radio" class="form-check-input" id="dbsearchttf" name="dbsearch" value="ttf" checked>
              <label class="form-check-label" for="dbsearchttf">Utiliser la base de donnée de tabletopfinder</label>
           </div>
           <div class="form-check form-check-inline">
               <input type="radio" class="form-check-input" id="dbsearchtrictrac" name="dbsearch" value="trictrac">
               <label class="form-check-label" for="dbsearchtrictrac">Utiliser la base de donnée de trictrac</label>
           </div>
        </div>
        <div class="card-footer">
            <input class="btn btn-primary btn-xs" type="submit" value="Chercher">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <a href="{% url 'jeu:create' 'ttf' 'empty' %}"  class="btn btn-info btn-xs" role="button">Ajouter à partir d'une feuille vierge</a>
        </div>
    </div>
    </div>
</form>
{% if games %}
<hr>
<form method="post">{% csrf_token %}

    <input type="hidden" name="dbsearch" id="dbsearch" value="{{ dbsearch }}">
    <div class="container">
    <div class="card border-primary">
        <div class="card-header text-center text-white bg-primary"><h3>Sélectionnez un jeu</h3></div>
        <div class="card-body">
          {% for game in games %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="game" id="game{{ game.gameID }}" value="{{ game.gameID }}">
                <label class="form-check-label" for="game{{ game.gameID }}">
                  {{ game.title }}
                </label>
            </div>
            <hr>
           {% endfor %}
        </div>
        <div class="card-footer">
            <input class="btn btn-success btn-xs" type="submit" value="Ajouter">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <a href="{% url 'jeu:create' 'ttf' 'empty' %}"  class="btn btn-info btn-xs" role="button">Ajouter à partir d'une feuille vierge</a>
        </div>
    </div>
    </div>
</form>
{% endif %}
{% endblock content %}

jeu/templates/jeu/game_detail.html
{% extends "common/base.html" %}
{% block content %}
<div class="container ">
<div class="card border-primary">
    <div class="card-header text-center text-white bg-primary"><h1>{{ object.title }}</h1></div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>description</h5></div>
          <div class="card-body scroll">{{ object.description }}</div>
      </div>
      <div class="card border-success">
          <div class="card-header text-center text-white bg-success"><h5>Localisation</h5></div>
          <div class="card-title text-center font-weight-bold">{{ object.localisation.name }}</div>
          <div class="container card-text scroll">{{ object.localisation.details }}</div>
      </div>
    </div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Genres</h5></div>
          <div class="card-body scroll">{% for genre in object.genres.all %} <p class="card-text">{{genre.name}}</p> {% endfor %}</div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Nombre de joueurs</h5></div>
          <div class="card-body scroll">
              <p class="card-text">{{object.playersmin}}-{{object.playersmax}}</p>
          </div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Temps de Jeu en minutes</h5></div>
          <div class="card-body scroll"><p class="card-text">{{object.timemin}}-{{object.timemax}}</p></div>
      </div>
    </div>
    <div class="card-deck pt-3 mb-3">
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Créateurs</h5></div>
          <div class="card-body scroll">{% for creator in object.creators.all %} <p class="card-text">{{creator}}</p> {% endfor %}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Autres informations</h5></div>
          <div class="card-body scroll">
              <p class="card-text">Age minimum {{ object.agemin }}</p>
              <p class="card-text">Prix {{ object.tarif }} euros</p>
              <p class="card-text">Extension {% if object.extension %}<i class="fas fa-check-circle" style="color:green"></i>
                                             {% else %}<i class="fas fa-times-circle" style="color:red"></i>{% endif %}
              </p>
          </div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Date de publication</h5></div>
          <div class="card-body scroll"><p class="card-text">{{object.date|date:"Y"}}</p></div>
       </div>
    </div>
    <div class="card-footer">
    <a href="{% url 'jeu:update' object.id %}" class="btn btn-warning btn-lg" role="button" aria-pressed="true">Editer</a>
    </div>
</div>
{% endblock content %}

jeu/templates/jeu/game_update_form.html
{% extends "common/base.html" %}
{% block content %}
<!-- Error message -->
{% if form.non_field_errors %}
  <span class="text-danger text-center">{{ form.non_field_errors }}</span>
{% endif %}
{% if form.non_form_errors %}
  <span class="text-danger text-center">{{ form.non_form_errors }}</span>
{% endif %}
<form method="post">{% csrf_token %}
    <div class="container">
<div class="card border-primary">
    <div class="card-header text-center text-white bg-primary"><h1>{{ form.title }}</h1></div>
    {% if form.title.errors %}
        <span class="text-danger"> {{ form.title.errors }} </span>
      {% endif %}
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>description</h5></div>
        {% if form.description.errors %}
        <span class="text-danger"> {{ form.description.errors }} </span>
        {% endif %}
          <div class="card-body">{{ form.description }}</div>
      </div>
      <div class="card border-success">
          <div class="card-header text-center text-white bg-success"><h5>Localisation</h5></div>
        {% if form.localisation.errors %}
        <span class="text-danger"> {{ form.localisation.errors }} </span>
        {% endif %}
          <div class="card-body text-center font-weight-bold" title="{{form.localisation.details}}">{{ form.localisation }}</div>
      </div>
    </div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Genres</h5></div>
        {% if form.genres.errors %}
        <span class="text-danger"> {{ form.genres.errors }} </span>
        {% endif %}
          <div class="card-body">{{form.genres}}</div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Nombre de joueurs</h5></div>
        {% if form.playermax.errors %}
        <span class="text-danger"> {{ form.playermax.errors }} </span>
        {% endif %}
          {% if form.playermin.errors %}
        <span class="text-danger"> {{ form.playermin.errors }} </span>
        {% endif %}
          <div class="card-body">
              <p class="card-text">Minimum</p>
              <p class="card-text">{{form.playersmin}}</p>
              <p class="card-text">Maximum</p>
              <p class="card-text">{{form.playersmax}}</p>
          </div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Temps de Jeu en mintues</h5></div>
        {% if form.timemin.errors %}
        <span class="text-danger"> {{ form.timemin.errors }} </span>
        {% endif %}
          <div class="card-body">
              <p class="card-text">Minimum</p>
              <p class="card-text">{{form.timemin}}</p>
              <p class="card-text">Maximum</p>
              <p class="card-text">{{form.timemax}}</p>
          </div>
      </div>
    </div>
    <div class="card-deck pt-3 mb-3">
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Créateurs</h5></div>
        {% if form.creators.errors %}
        <span class="text-danger"> {{ form.creators.errors }} </span>
        {% endif %}
          <div class="card-body">{{form.creators}}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Autres informations</h5></div>
         {% if form.agmin.errors %}
        <span class="text-danger"> {{ form.agemin.errors }} </span>
        {% endif %}
            {% if form.tarif.errors %}
        <span class="text-danger"> {{ form.tarif.errors }} </span>
        {% endif %}
            {% if form.agmin.errors %}
        <span class="text-danger"> {{ form.extension.errors }} </span>
        {% endif %}
          <div class="card-body">
              <p class="card-text">Age Minimum</p>
              <p class="card-text">{{form.agemin}}</p>
              <p class="card-text">Tarif en euros</p>
              <p class="card-text">{{form.tarif}}</p>
              <p class="card-text">C'est une extension</p>
              <p class="card-text">{{form.extension}}</p>
          </div>
          </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Date de publication</h5></div>
        {% if form.date.errors %}
        <span class="text-danger"> {{ form.date.errors }} </span>
        {% endif %}
          <div class="card-body"><p class="card-text">{{form.date}}</p></div>
       </div>
    </div>
    <div class="card-footer">
        <input class="btn btn-primary btn-xs" type="submit" value="Sauver">
        <input class="btn btn-warning btn-xs" type="reset" value="Reset">
    </div>
    </div>
</form>
{% if messages %}
<div class="container">
<div class="card border-primary">
    <div class="card-body">
        <p class="card-text">Pour plus d'information vous pouvez regarder :</p>
    {% for message in messages %}
        <p class="card-text"><a href="{{ message }}">{{ message }}</a></p>
    {% endfor %}
    </div>
</div>
</div>
{% endif %}
{% endblock content %}

jeu/templates/jeu/search_game.html
{% extends "common/base.html" %}
{% block content %}
<!-- Error message -->
{% if form.non_field_errors %}
  <span class="text-danger text-center">{{ form.non_field_errors }}</span>
{% endif %}
{% if form.non_form_errors %}
  <span class="text-danger text-center">{{ form.non_form_errors }}</span>
{% endif %}

<div class="container">
<form method="get" action="{% url 'jeu:search' %}">
    <div class="container">
    <div class="card border-info">
        <div class="card-header text-center text-white bg-info"><h3>Jeux à rechercher</h3></div>
        <div class="card-body">
            <div class="form-row">
                <div class="col">
                    <input class="form-control" id="id_search_field" title="Pattern" placeholder="Pattern" type="text" name="search_field" value="">
                </div>
                <div class="col">
                    <input class="form-control" id="id_max_time" title="temps de jeu" placeholder="temps de jeu" min="1" type="number" name="max_time" value="">
                </div>
                <div class="col">
                    <input class="form-control" id="id_nb_play" title="nombre de joueurs" placeholder="nombre de joueurs" min="1" type="number" name="nb_play" value="">
                </div>
            </div>
        </div>
        <div class="card-footer md-3">
            <input class="btn btn-primary btn-xs" type="submit" value="Rechercher">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <span class="float-right">Vous avez {{ nbr_games }} jeux pour une valeur totale de {{ valeur.tarif__sum|floatformat:"-2" }} euros</span>
        </div>
    </div>
    </div>
</form>
{% if game_list %}
<hr>
<div class="card" >
    <div class="card-header text-center font-weight-bold">
    Liste des Jeux qui match {{ view_search_field }}
  </div>
    <div class="card-body">
<table id="ludogotable" class="table display">
    <thead class="thead-light">
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Genres</th>
            <th scope="col">Nombre de Joueurs min-max</th>
            <th scope="col">Temps en minutes min-max</th>
            <th scope="col">Age recommandé</th>
            <th scope="col">Localisation</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for game in game_list %}
    <tr>
      <td><a href="{% url 'jeu:detail' game.id %}">{{ game.title }}</a></td>
      <td>{% for genre in game.genres.all %}{{genre.name}} {% endfor %}</td>
      <td>{{ game.playersmin }}-{{ game.playersmax }}</td>
      <td>{{ game.timemin }}-{{ game.timemax }}</td>
      <td>{{ game.agemin }}</td>
      <td>{{ game.localisation }}</td>
      <td>
        <a class="btn btn-link float-right"
                     href="{% url 'jeu:delete' game.id %}">
                    <i class="far fa-trash-alt text-danger float-right"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    </div>
</div>
{% endif %}
</div>
{% endblock content %}