jeu/urls.py
# coding=utf-8
from django.urls import path
from .views import searchgame, GameListView, GameDetailView, GameDeleteView, GameUpdateView, GameCreateView

app_name = 'jeu'
urlpatterns = [
    path(r'addnew', searchgame, name="addnew"),
    path(r'search', GameListView.as_view(), name="search"),
    path(r'addnew/<slug:dbsearch>/<slug:db_id>', GameCreateView.as_view(), name="create"),
    path(r'<int:game_id>', GameDetailView.as_view(), name="detail"),
    path(r'update/<int:game_id>', GameUpdateView.as_view(), name="update"),
    path(r'delete/<int:game_id>', GameDeleteView.as_view(), name="delete"),
]

ludogo/urls.py
# coding=utf-8
"""ludogo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path(r'', HomeView.as_view(), name="home"),
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'movie/', include('film.urls', namespace="film")),
    path(r'game/', include('jeu.urls', namespace="jeu")),
]

common/models.py
# coding=utf-8
from django.db import models

# Create your models here.


class Genre(models.Model):
    TYPE_MOVIE = 'film'
    TYPE_GAME = 'jeu'
    TYPE_CHOICES = ((TYPE_MOVIE, 'film'), (TYPE_GAME, 'jeu'))
    name = models.CharField(max_length=100, help_text='Nom du genre')
    type = models.CharField(max_length=100, help_text='Type du genre', choices=TYPE_CHOICES)
    description = models.CharField(max_length=150, help_text='Une courte description du genre', blank=True)

    class Meta:
        unique_together = ['name', 'type']

    def __str__(self):
        return "{} {}".format(self.type, self.name)


class Person(models.Model):
    firstname = models.CharField(max_length=100, help_text='Prenom')
    lastname = models.CharField(max_length=100, help_text='Nom de Famille')


    class Meta:
        unique_together = ['firstname', 'lastname']

    def __str__(self):
        return "{} {}".format(self.firstname, self.lastname)


class Localisation(models.Model):
    name = models.CharField(max_length=100, help_text='Nom du lieu')
    details = models.CharField(max_length=100, help_text="details de l'emplacement")

    class Meta:
        unique_together = ['name', 'details']

    def __str__(self):
        return "{} {}".format(self.name, self.details)

common/views.py
from django.shortcuts import render

# Create your views here.

common/templates/common/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE HTML>
<html lang="fr">
<head>
  <title>Ludogo</title>
  <meta charset="utf-8"/>
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Ludogo site"/>
  <meta name="author" content="Fabien Mareuil"/>
  <link rel="shortcut icon" href="{% static 'common/images/ludogo_icon.png' %}"
        type="image/png">
  <meta http-equiv="content-type" content="text/html;"/>  
  {% block stylesheet %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
        crossorigin="anonymous">
  <!-- Boostrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css"
          href="{% static 'common/css/ludogo.css' %}"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
  {% endblock stylesheet %}
</head>

<body>
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'common/images/ludogo_icon.png' %}" width="30" height="30" alt="Ludogo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Ludogo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'film:search' %}">Rechercher un Film</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'film:addnew' %}">Ajouter un nouveau film</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jeu:search' %}">Rechercher un Jeu</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jeu:addnew' %}">Ajouter un nouveau Jeu</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}
{% block content %}
{% endblock content %}
{% block footer %}
  <!-- SiteMap -->
  <footer class="page-footer">
    <div class="container text-center">

        <a class="text-muted" href="{% url 'home' %}">Home</a> |
        {% load admin_urls %}
        <a class="text-muted" href="#">documentation</a>
        |
        <a href="{% url 'admin:index' %}">Admin</a>

      </div>
  </footer>

  <!-- Modal -->
  <div class="modal fade confirm-modal" id="confirm-modal" tabindex="-1"
       role="dialog"
       aria-labelledby="ConfirmationBox" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
      <div class="modal-content text-center">
        <div class="modal-body">
          <i class="text-warning fas fa-exclamation-triangle fa-4x"></i>
          <h4 class="modal-title" id="exampleModalLongTitle">
            Are you sure ?
          </h4>
        </div>
        <div class="modal-footer  justify-content-center">
          <button id='cancel-button' type="button"
                  class="btn btn-secondary" data-dismiss="modal">
            Cancel
          </button>
          <button id="ok-button" type="button" class="btn btn-primary">
            Ok
          </button>
        </div>
      </div>
    </div>
  </div>
{% endblock footer %}
{% block js %}
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
 <script type="text/javascript">
    $(document).ready(function() {
    $('#ludogotable').DataTable( {
        "order": [],
        "columnDefs": [{"orderable": false, "targets": -1}]
    } );
    } );
 </script>
{% endblock js %}
</body>
</html>

common/templates/common/confirm_delete.html
{% extends "common/base.html" %}
{% block content %}
<div class="jumbotron">
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.title }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
    <button onclick="window.history.back();" class="btn" type="button">Cancel</button>
</form>
</div>
{% endblock content %}

common/templates/common/home.html
{% extends "common/base.html" %}
{% load static %}
{% block content %}
    <div class="card-body">
        <div class="card-deck pt-2" >

            <div class="card border-success">
                <a href="{% url 'film:addnew' %}">
                    <div class="card-header text-center text-white bg-success"><h3>Ajouter un nouveau film</h3></div>
                        <img class="card-img-top" src="{% static 'common/images/add_movie.png' %}" alt="add movie"/>
                </a>
            </div>
            <div class="card border-success">
                <a href="{% url 'jeu:addnew' %}">
                    <div class="card-header text-center text-white bg-success"><h3>Ajouter un nouveau jeu</h3></div>
                    <img class="card-img-top" src="{% static 'common/images/add_game.png' %}" alt="add game">
                    <div class="card-body"></div>

                </a>
            </div>

            <div class="card border-info">
                <a href="{% url 'film:search' %}">
                    <div class="card-header text-center text-white bg-info"><h3>Chercher un film</h3></div>
                    <img class="card-img-top"  src="{% static 'common/images/search_movie.png' %}" alt="search movie">
                    <div class="card-body"></div>
                </a>
            </div>
            <div class="card border-info">
                <a href="{% url 'jeu:search' %}">
                    <div class="card-header text-center text-white bg-info"><h3>Chercher un jeu</h3></div>
                    <img class="card-img-top" src="{% static 'common/images/search_game.png' %}" alt="search game">
                    <div class="card-body"></div>
                </a>
            </div>
        </div>
{% endblock %}