film/urls.py
# coding=utf-8
from django.urls import path
from .views import MovieDetailView, MovieUpdateView, MovieCreateView, searchmovie, MovieListView, MovieDeleteView

app_name = 'film'
urlpatterns = [
    path(r'addnew', searchmovie, name="addnew"),
    path(r'search', MovieListView.as_view(), name="search"),
    path(r'addnew/<slug:imdb_id>', MovieCreateView.as_view(), name="create"),
    path(r'<int:movie_id>', MovieDetailView.as_view(), name="detail"),
    path(r'update/<int:movie_id>', MovieUpdateView.as_view(), name="update"),
    path(r'delete/<int:movie_id>', MovieDeleteView.as_view(), name="delete"),
]

jeu/urls.py
# coding=utf-8
from django.urls import path
from .views import searchgame, GameListView, GameDetailView, GameDeleteView, GameUpdateView, GameCreateView

app_name = 'jeu'
urlpatterns = [
    path(r'addnew', searchgame, name="addnew"),
    path(r'search', GameListView.as_view(), name="search"),
    path(r'addnew/<slug:dbsearch>/<slug:db_id>', GameCreateView.as_view(), name="create"),
    path(r'<int:game_id>', GameDetailView.as_view(), name="detail"),
    path(r'update/<int:game_id>', GameUpdateView.as_view(), name="update"),
    path(r'delete/<int:game_id>', GameDeleteView.as_view(), name="delete"),
]

ludogo/urls.py
# coding=utf-8
"""ludogo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path(r'', HomeView.as_view(), name="home"),
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'movie/', include('film.urls', namespace="film")),
    path(r'game/', include('jeu.urls', namespace="jeu")),
]

film/models.py
# coding=utf-8
from django.db import models
from common.models import Genre, Person, Localisation

# Create your models here.


class Format(models.Model):
    name = models.CharField(max_length=100, help_text='Nom du format', unique=True)
    description = models.CharField(max_length=100, help_text='Rapide description du format', blank=True)

    def __str__(self):
        return self.name


class Langue(models.Model):
    name = models.CharField(max_length=100, help_text='Nom du format', unique=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    TT_PUBLIC = "tous publics"
    TT_PUBLICW = "tous publics (avec avertissement)"
    DIX = "10"
    DOUZE = "12"
    SEIZE = "16"
    DIXHUIT = "18"
    X = "X"
    TYPE_CERTIF = ((TT_PUBLIC, 'Tous publics'), (TT_PUBLICW, 'Tous publics (avec avertissement)'), (DIX, 'plus de 10ans'),
                   (DOUZE,'plus de 12ans'), (SEIZE, 'plus de 16ans'), (DIXHUIT, 'plus de 18ans'), (X, 'Adulte'))
    title = models.CharField(max_length=300, help_text='Titre du film original')
    french_title = models.CharField(max_length=300, help_text='Titre du film français')
    synopsis = models.TextField(help_text='synopsis du film')
    genres = models.ManyToManyField(Genre, help_text='genres du film')
    date = models.DateTimeField()
    actors = models.ManyToManyField(Person, help_text='acteurs principaux du film', related_name='actors')
    realisators = models.ManyToManyField(Person, help_text='realisateurs du film', related_name='realisators')
    format = models.ForeignKey(Format, help_text="format du film", on_delete=models.DO_NOTHING)
    langue = models.ForeignKey(Langue, help_text="langue.s du film", on_delete=models.DO_NOTHING)
    localisation = models.ForeignKey(Localisation, help_text="lieu où est le film", on_delete=models.DO_NOTHING)
    certificate = models.CharField(max_length=50, help_text='certification', choices=TYPE_CERTIF)

    class Meta:
        unique_together = ['title', 'format', 'langue']

    def __str__(self):
        return self.title

film/forms.py
# coding=utf-8
from django.forms.models import ModelForm
from django import forms
from .models import Movie
from common.models import Genre, Person


class MovieForm(ModelForm):
    note = forms.CharField(max_length=150)
    certificates = forms.CharField(max_length=300)
    date = forms.DateField(
        widget=forms.DateInput(format='%Y', attrs={'class': 'datepicker'}),
        input_formats=('%Y',)
    )

    def __init__(self, *args, **kwargs):
        super(MovieForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            if visible.field.label in ['Title', 'French_title', 'Genres', 'Format', 'Langue', 'Localisation', 'Date',
                                       'Certificate']:
                visible.field.required = True
            else:
                visible.field.required = False
            if visible.field.label in ['Actors', 'Realisators', 'Genres']:
                visible.field.widget.attrs['size'] = 10
        self.fields['genres'].queryset = Genre.objects.filter(type=Genre.TYPE_MOVIE)
        self.fields['actors'].queryset = Person.objects.all().order_by('firstname')
        self.fields['realisators'].queryset = Person.objects.all().order_by('firstname')

    class Meta:
        model = Movie
        fields = ('title','french_title', 'synopsis', 'genres', 'date', 'actors', 'realisators', 'format', 'langue',
                  'localisation', 'certificate')
        widgets = {
            'actors': forms.SelectMultiple,
            'realisators': forms.SelectMultiple,
            'genres': forms.SelectMultiple,
        }


class MovieListForm(ModelForm):
    search_field = forms.CharField(max_length=250)

film/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Q, Count
from .models import Movie
from .forms import MovieForm, MovieListForm
from common.models import Genre, Person
from django.urls import reverse_lazy
from collections import Counter

from imdb import Cinemagoer
import datetime
import random as rand
import re

# Create your views here.


class MovieDetailView(generic.DetailView):
    model = Movie
    pk_url_kwarg = 'movie_id'


class MovieUpdateView(generic.UpdateView):
    model = Movie
    form_class = MovieForm
    pk_url_kwarg = 'movie_id'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy("film:detail")

    def get_success_url(self):
        return reverse_lazy('film:detail', kwargs=self.kwargs)


class MovieCreateView(generic.CreateView):
    model = Movie
    form_class = MovieForm
    template_name_suffix = '_update_form'

    def get_initial(self):
        if self.kwargs['imdb_id'] != 'empty':
            ia = Cinemagoer()
            movie = ia.get_movie(self.kwargs['imdb_id'])
            fraka = get_aka(movie['aka'][0])
            newmovie = {}
            if 'synopsis' in movie:
                newmovie['synopsis'] = movie['synopsis'][0]
            elif 'plot outline' in movie:
                newmovie['synopsis'] = movie['plot outline']
            elif 'plot' in movie:
                newmovie['synopsis'] = movie['plot'][0].split('::')[0]
            if 'title' in movie:
                newmovie['title'] = movie['title']
            if 'year' in movie:
                newmovie['date'] = datetime.datetime(movie['year'], 1, 1)
            if fraka:
                newmovie['french_title'] = fraka
            listg = []
            if not 'genres' in movie:
                movie['genres'] = []
            for genre in movie['genres']:
                g = Genre.objects.get_or_create(type=Genre.TYPE_MOVIE, name=genre)
                listg.append(g[0].id)
            newmovie['genres'] = listg
            if 'cast' in movie:
                listact = []
                for actor in movie['cast'][0:6]:
                    name = actor['long imdb canonical name'].split(',')
                    if len(name) > 1:
                        ac = Person.objects.get_or_create(firstname=name[1], lastname=name[0])
                    else:
                        ac = Person.objects.get_or_create(firstname='', lastname=name[0])
                    listact.append(ac[0].id)
                newmovie['actors'] = listact
            listreal = []
            if not 'directors' in movie:
                movie['directors'] = []
            for realisator in movie['directors']:
                realname = realisator['long imdb canonical name'].split(',')
                if len(realname) > 1:
                    real = Person.objects.get_or_create(firstname=realname[1], lastname=realname[0])
                else:
                    real = Person.objects.get_or_create(firstname='', lastname=realname[0])
                listreal.append(real[0].id)
            newmovie['realisators'] = listreal
            if 'certificates' in movie:
                for certif in movie['certificates']:
                    if 'France' in certif:
                        newmovie['certificate'] = certif.split(':')[1].lower()
                if not 'certificate' in newmovie:
                    newmovie['certificates'] = ', '.join(movie['certificates'])
            if 'rating' in movie:
                newmovie['note'] = movie['rating']
        else:
            newmovie = {}
        return newmovie

    def get_success_url(self):
        return reverse_lazy('film:detail', kwargs={'movie_id':self.object.pk})


def searchmovie(request):
    if request.method == "GET":
        ia = Cinemagoer()
        newmovie = request.GET.get('newmovie', None)
        if newmovie:
            result = ia.search_movie(newmovie)
        else:
            result = []
        movies = []
        for movie in result:
            if movie['kind'] == 'movie':
                dic_movie = {}
                if 'aka' in movie.keys():
                    dic_movie['aka'] = movie['aka']
                if 'long imdb canonical title' in movie.keys():
                    dic_movie['imdb_title'] = movie['long imdb canonical title']
                if 'title' in movie.keys():
                    dic_movie['title'] = movie['title']
                if 'year' in movie.keys():
                    dic_movie['year'] = movie['year']
                dic_movie['movieID'] = movie.movieID
                movies.append(dic_movie)
        return render(request, 'film/addnew_movie.html', {'movies': movies})
    elif request.method == "POST":
        if 'movie' in request.POST:
            return redirect(reverse_lazy('film:create', kwargs={'imdb_id':request.POST['movie']}))
        else:
            return redirect(reverse_lazy('film:create', kwargs={'imdb_id': 'empty'}))
    else:
        return render(request, 'film/addnew_movie.html')

def get_aka(aka):
    akas = re.sub(' +',' ', aka).split('\n \n \n')
    fr_aka = ""
    for aka in akas:
        if 'France' in aka:
            fr_aka = str(aka.split('\n')[0].strip())
    return fr_aka


class MovieListView(generic.ListView):
    model = Movie
    form_class = MovieListForm
    template_name = 'film/search_movie.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MovieListView,self).get_context_data(**kwargs)
        searchfield = self.request.GET.get('search_field',None)
        searchactors = self.request.GET.get('search_actors',None)
        searchrealisators = self.request.GET.get('search_realisators',None)
        if searchfield or searchactors or searchrealisators:
            context['view_search_field'] = ' '.join([searchfield, searchactors, searchrealisators])
        context['nbr_movies'] = self.model.objects.count()
        return context

    def search_patterns(self, pattern, object_list):
        patterns = pattern.split()
        for pat in patterns:
            olist = self.model.objects.filter(Q(title__icontains=pat.strip()) |
                                              Q(french_title__icontains=pat.strip()) |
                                              Q(genres__name__icontains=pat.strip()))
            object_list = object_list.union(olist, all=True)
        return object_list

    def search_actors(self, pattern, object_list):
        patterns = pattern.split()
        for pat in patterns:
            olist = self.model.objects.filter(Q(actors__firstname__icontains=pat.strip()) |
                                              Q(actors__lastname__icontains=pat.strip()))
            object_list = object_list.union(olist, all=True)
        return object_list

    def search_realisators(self, pattern, object_list):
        patterns = pattern.split()
        for pat in patterns:
            olist = self.model.objects.filter(Q(realisators__firstname__icontains=pat.strip()) |
                                              Q(realisators__lastname__icontains=pat.strip()))
            object_list = object_list.union(olist, all=True)
        return object_list

    def get_queryset(self):
        pattern = self.request.GET.get('search_field',None)
        actor_pattern = self.request.GET.get('search_actors',None)
        realisator_pattern = self.request.GET.get('search_realisators',None)
        random = self.request.GET.get('random',None)
        object_list = self.model.objects.none()
        if pattern:
            object_list = self.search_patterns(pattern, object_list)
        if actor_pattern:
            object_list = self.search_actors(actor_pattern, object_list)
        if realisator_pattern:
            object_list = self.search_realisators(realisator_pattern, object_list)
        if random == 'yes':
            l = list(self.model.objects.values_list('id', flat=True))
            if len(l) > 0:
                olist = self.model.objects.filter(id=rand.choice(l))
                object_list = object_list.union(olist, all=True)
        result = [item for items, c in Counter(list(object_list.values_list('id', flat=True))).most_common()
                  for item in [items] * c]
        uniqresult = []
        for n in result:
            if not n in uniqresult:
                uniqresult.append(n)
        clauses = ' '.join(['WHEN id=%s THEN %s' % (pk, i) for i, pk in enumerate(uniqresult)])
        ordering = 'CASE %s END' % clauses
        queryset = self.model.objects.filter(pk__in=uniqresult).extra(
            select={'ordering': ordering}, order_by=('ordering',))
        return queryset


class MovieDeleteView(generic.DeleteView):
    model = Movie
    template_name = 'common/confirm_delete.html'
    pk_url_kwarg = 'movie_id'

    def get_success_url(self):
        return reverse_lazy('film:search')

film/templates/film/addnew_movie.html
{% extends "common/base.html" %}

{% block content %}
<form method="get" action="{% url 'film:addnew' %}">
    <div class="container">
    <div class="card border-success">
        <div class="card-header text-center text-white bg-success"><h3>Titre du film à ajouter</h3></div>
        <div class="card-body">
          <input class="form-control" id="id_newmovie"
                 placeholder="Entrez un titre" type="text" name="newmovie"
                 value="{{ newmovietitle }}"
                 aria-describedby="newmovieHelp"/>
          <small id="newmovieHelp" class="form-text text-muted">un titre complet ou juste un morceau du titre est suffisant
          </small>
        </div>
        <div class="card-footer">
            <input class="btn btn-primary btn-xs" type="submit" value="Chercher">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <a href="{% url 'film:create' 'empty' %}"  class="btn btn-info btn-xs" role="button">Ajouter à partir d'une feuille vierge</a>
        </div>
    </div>
    </div>
</form>
{% if movies %}
<hr>
<form method="post">{% csrf_token %}
    <div class="container">
    <div class="card border-primary">
        <div class="card-header text-center text-white bg-primary"><h3>Sélectionnez un film</h3></div>
        <div class="card-body">
          {% for movie in movies %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="movie" id="movie{{ movie.movieID }}" value="{{ movie.movieID }}">
                <label class="form-check-label" for="movie{{ movie.movieID }}">
                  {{ movie.imdb_title }} {{ movie.title }} {{ movie.year }} {% if movie.aka %}{% for aka in movie.aka %}{{aka}}{% endfor %}{% endif %}
                </label>
            </div>
            <hr>
           {% endfor %}
        </div>
        <div class="card-footer">
            <input class="btn btn-success btn-xs" type="submit" value="Ajouter">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <a href="{% url 'film:create' 'empty' %}"  class="btn btn-info btn-xs" role="button">Ajouter à partir d'une feuille vierge</a>
        </div>
    </div>
    </div>
</form>
{% endif %}
{% endblock content %}

film/templates/film/movie_detail.html
{% extends "common/base.html" %}
{% block content %}
<div class="container ">
<div class="card border-primary">
    <div class="card-header text-center text-white bg-primary"><h1>{{ object.title }}</h1>
        {{ object.french_title }}</div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>synopsis</h5></div>
          <div class="card-body scroll">{{ object.synopsis }}</div>
      </div>
      <div class="card border-success">
          <div class="card-header text-center text-white bg-success"><h5>Localisation</h5></div>
          <div class="card-title text-center font-weight-bold">{{ object.localisation.name }}</div>
          <div class="container card-text scroll">{{ object.localisation.details }}</div>
      </div>
    </div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Genres</h5></div>
          <div class="card-body scroll">{% for genre in object.genres.all %} <p class="card-text">{{genre.name}}</p> {% endfor %}</div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Format</h5></div>
          <div class="card-body scroll"><p class="card-text">{{object.format}}</p></div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Langue</h5></div>
          <div class="card-body scroll"><p class="card-text">{{object.langue}}</p></div>
      </div>
    </div>
    <div class="card-deck pt-3 mb-3">
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Acteurs</h5></div>
          <div class="card-body scroll">{% for actor in object.actors.all %} <p class="card-text">{{actor}}</p> {% endfor %}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Réalisateurs</h5></div>
          <div class="card-body scroll">{% for realisator in object.realisators.all %} <p class="card-text">{{realisator}}</p> {% endfor %}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Autres informations</h5></div>
          <div class="card-body scroll">
              <p class="card-text">Date de sortie</p>
              <p class="card-text">{{object.date|date:"Y"}}</p>
              <p class="card-text">Publics</p>
              <p class="card-text">{{object.certificate}}</p>
          </div>
       </div>
    </div>
    <div class="card-footer">
    <a href="{% url 'film:update' object.id %}" class="btn btn-warning btn-lg" role="button" aria-pressed="true">Editer</a>
    </div>
</div>
{% endblock content %}

film/templates/film/movie_update_form.html
{% extends "common/base.html" %}
{% block content %}
<!-- Error message -->
{% if form.non_field_errors %}
  <span class="text-danger text-center">{{ form.non_field_errors }}</span>
{% endif %}
{% if form.non_form_errors %}
  <span class="text-danger text-center">{{ form.non_form_errors }}</span>
{% endif %}

<form method="post">{% csrf_token %}
    <div class="container">
<div class="card border-primary">
    <div class="card-header text-center text-white bg-primary"><h1>{{ form.title }}</h1>
    {{ form.french_title }}
    {% if form.note.value %}
    <span class="small">
        Note IMDB: {{ form.note.value }}
    </span></div>
    {% endif %}
    {% if form.title.errors %}
        <span class="text-danger"> {{ form.title.errors }} </span>
      {% endif %}
    {% if form.french_title.errors %}
        <span class="text-danger"> {{ form.french_title.errors }} </span>
      {% endif %}
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>synopsis</h5></div>
        {% if form.synopsis.errors %}
        <span class="text-danger"> {{ form.synopsis.errors }} </span>
        {% endif %}
          <div class="card-body">{{ form.synopsis }}</div>
      </div>
      <div class="card border-success">
          <div class="card-header text-center text-white bg-success"><h5>Localisation</h5></div>
        {% if form.localisation.errors %}
        <span class="text-danger"> {{ form.localisation.errors }} </span>
        {% endif %}
          <div class="card-body text-center  font-weight-bold" title="{{form.localisation.details}}">{{ form.localisation }}</div>
      </div>
    </div>
    <div class="card-deck pt-3">
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Genres</h5></div>
        {% if form.genres.errors %}
        <span class="text-danger"> {{ form.genres.errors }} </span>
        {% endif %}
          <div class="card-body">{{form.genres}}</div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Format</h5></div>
        {% if form.format.errors %}
        <span class="text-danger"> {{ form.format.errors }} </span>
        {% endif %}
          <div class="card-body"><p class="card-text">{{form.format}}</p></div>
      </div>
      <div class="card border-info">
          <div class="card-header text-center text-white bg-info"><h5>Langue</h5></div>
        {% if form.langue.errors %}
        <span class="text-danger"> {{ form.langue.errors }} </span>
        {% endif %}
          <div class="card-body"><p class="card-text">{{form.langue}}</p></div>
      </div>
    </div>
    <div class="card-deck pt-3 mb-3">
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Acteurs</h5></div>
        {% if form.actors.errors %}
        <span class="text-danger"> {{ form.actors.errors }} </span>
        {% endif %}
          <div class="card-body">{{form.actors}}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Réalisateurs</h5></div>
         {% if form.realisators.errors %}
        <span class="text-danger"> {{ form.realisators.errors }} </span>
        {% endif %}
          <div class="card-body">{{form.realisators}}</div>
        </div>
        <div class="card border-secondary">
          <div class="card-header text-center text-white bg-secondary"><h5>Autres informations</h5></div>
        {% if form.date.errors %}
        <span class="text-danger"> {{ form.date.errors }} </span>
        {% endif %}
        {% if form.certificate.errors %}
        <span class="text-danger"> {{ form.certificate.errors }} </span>
        {% endif %}
          <div class="card-body">
              <p class="card-text">Date de sortie</p>
              <p class="card-text">{{form.date}}</p>
              <p class="card-text">Publics</p>
              <p class="card-text">{{form.certificate}}</p>
              {% if form.certificates.value %}
              <span class="small">{{form.certificates.value}}</span>
              {% endif %}
          </div>
       </div>
    </div>
    <div class="card-footer">
        <input class="btn btn-primary btn-xs" type="submit" value="Sauver">
        <input class="btn btn-warning btn-xs" type="reset" value="Reset">
    </div>
    </div>
</form>
{% endblock content %}

film/templates/film/search_movie.html
{% extends "common/base.html" %}
{% block content %}
<!-- Error message -->
{% if form.non_field_errors %}
  <span class="text-danger text-center">{{ form.non_field_errors }}</span>
{% endif %}
{% if form.non_form_errors %}
  <span class="text-danger text-center">{{ form.non_form_errors }}</span>
{% endif %}

<form method="get" action="{% url 'film:search' %}">
    <div class="container">
    <div class="card border-info">
        <div class="card-header text-center text-white bg-info"><h3>Films à rechercher</h3></div>
        <div class="card-body">
            <div class="form-row">
                <div class="col">
                    <input class="form-control" id="id_search_field" placeholder="Titre ou genre" type="text" name="search_field" value="">
                </div>
                <div class="col">
                    <input class="form-control" id="id_search_actors" placeholder="Acteurs" type="text" name="search_actors" value="">
                </div>
                <div class="col">
                    <input class="form-control" id="id_search_realisators" placeholder="Réalisateurs" type="text" name="search_realisators" value="">
                </div>
            </div>
        </div>
        <div class="card-footer md-3">
            <input class="btn btn-primary btn-xs" type="submit" value="Rechercher">
            <input class="btn btn-warning btn-xs" type="reset" value="Reset">
            <a href="{% url 'film:search' %}?random=yes"  class="btn btn-info btn-xs" role="button">Trouve moi un film</a>
            <span class="float-right">Vous avez {{ nbr_movies }} films</span>
        </div>
    </div>
    </div>
</form>
{% if movie_list %}
<hr>
<div class="container">
<div class="card border" >
    <div class="card-header text-center font-weight-bold">
    Liste des Films qui match {{ view_search_field }}
  </div>
    <div class="card-body">
<table id="ludogotable" class="table border">
    <thead class="thead-light">
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Genres</th>
            <th scope="col">Langue</th>
            <th scope="col">Format</th>
            <th scope="col">Date de Sortie</th>
            <th scope="col">Age conseillé</th>
            <th scope="col">Localisation</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for movie in movie_list %}
    <tr>
        <td><a href="{% url 'film:detail' movie.id %}">{{ movie.french_title }}<p><small>{{ movie.title }}</small></p></a></td>
      <td>{% for genre in movie.genres.all %}{{genre.name}} {% endfor %}</td>
      <td>{{ movie.langue }}</td>
      <td>{{ movie.format }}</td>
      <td>{{ movie.date|date:"Y"}}</td>
      <th>{{ movie.certificate }}</th>
      <td>{{ movie.localisation }}</td>
      <td>
        <a class="btn btn-link float-right"
                     href="{% url 'film:delete' movie.id %}">
                    <i class="far fa-trash-alt text-danger float-right"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    </div>
</div>
</div>
{% endif %}
{% endblock content %}